{"name": "test_login[cases3]", "status": "passed", "attachments": [{"name": "log", "source": "c5985f4a-f52b-47ec-8cfb-d9db2286ebb7-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c95605f1-98d5-420c-86d5-d690631816b2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "cases", "value": "{'title': '账号错误', 'phone': '18684720554', 'pwd': 'python', 'expected': '此账号没有经过授权，请联系管理员!'}"}], "start": 1602904196463, "stop": 1602904197221, "uuid": "ddf1290e-d0a4-4171-87cc-57d05dcb85b2", "historyId": "a85d84083a5782bac6aba2b322b79d31", "testCaseId": "1acd35a1f9ad0b5d30e9264cda6d4b81", "fullName": "testcase.test_login_case.Test_Login#test_login", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login_case"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "MS-KIXJBDXSQJIS"}, {"name": "thread", "value": "15584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login_case"}]}